version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build Docker image for running node tests
          command: docker build -t plaid-node .
      - run:
          name: Run node tests in Docker
          command: docker run --rm -e 6218561cf482bb001afe38b5=$6218561cf482bb001afe38b5 -e 55a29f1168f0e302bfe6f12d0f71e2=$55a29f1168f0e302bfe6f12d0f71e2 plaid-node
