version: 2

jobs:
  build:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make setup
      - run:
          name: Tests
          command: make test
